// Exports the chosen portfolio shots (by contact-sheet index) into web-sized WebP for the site.
// Usage: node export.mjs  → ../site/img/<name>-<n>.webp (+ -s.webp thumbs) and ../site/photos.js
// Order of PICKS = order within each category; the first photo of each set is its strongest.
import fs from "fs";
import path from "path";
import sharp from "sharp";

const PICKS = [
  { name: "ice-hall", sheet: "drive", cat: "igaming", title: "ICE London · show floor", idx: [0] },
  { name: "sigma-new", sheet: "nowe", cat: "igaming", title: "SiGMA Europe · Malta", idx: [4, 15, 6, 0, 12, 9, 8, 1, 14, 3, 5, 2] },
  { name: "sigma", sheet: "sigma", cat: "igaming", title: "SiGMA Europe · Malta", idx: [6, 16, 13, 24] },
  { name: "everymatrix", sheet: "em-d2", cat: "igaming", title: "EveryMatrix · ICE London", idx: [64, 12, 22, 60, 47, 15, 4, 3, 38, 82] },
  { name: "everymatrix-d1", sheet: "em-d1", cat: "igaming", title: "EveryMatrix · ICE London", idx: [0, 1, 26, 54, 63, 20] },
  { name: "everymatrix-new", sheet: "nowe", cat: "igaming", title: "EveryMatrix · ICE London", idx: [17] },
  { name: "flyfish", sheet: "flyfish", cat: "igaming", title: "Flyfish · ICE London", idx: [1, 18, 20, 11, 34] },
  { name: "valyuz", sheet: "flyfish", cat: "igaming", title: "Valyuz · ICE London", idx: [36] },
  { name: "sigma-award", sheet: "tasikn", cat: "igaming", title: "SiGMA Awards", idx: [15] },
  { name: "flat-gzira", sheet: "flat-marco", cat: "realestate", title: "Apartment · Gżira", idx: [18, 23, 0, 11, 27, 4, 24, 10] },
  { name: "flat-xbiex", sheet: "flat-xbiex", cat: "realestate", title: "Apartment · Ta' Xbiex", idx: [11, 19, 22, 26, 0, 32] },
  { name: "architecture", sheet: "tasikn", cat: "realestate", title: "Commercial architecture · Malta", idx: [26, 35, 29, 38] },
  { name: "birthday", sheet: "chantelle", cat: "private", title: "Private 40th birthday", idx: [20, 2, 12, 19, 27, 29, 3, 24] },
  { name: "xerjoff", sheet: "skybeach", cat: "brand", title: "Xerjoff × Scentoniq launch", idx: [2, 11, 12, 18, 39] },
  { name: "rolex", sheet: "rolex", cat: "brand", title: "Rolex Middle Sea Race", idx: [17, 0, 12, 18, 28, 34] },
  { name: "gianpula", sheet: "gianpula", cat: "brand", title: "Gianpula Village · live show", idx: [5, 13, 1, 20, 9] },
  { name: "bpro", sheet: "bpro-targi", cat: "brand", title: "B-PRO Systems · Beauty Expo", idx: [8, 2, 20, 30] },
  { name: "cargo", sheet: "cargo", cat: "brand", title: "Cargo · company party", idx: [12, 26, 32] },
  { name: "flirt", sheet: "aria", cat: "brand", title: "Flirt · Aria Complex", idx: [18, 3, 22] },
  { name: "aga", sheet: "drive", cat: "about", title: "Aga Fierek at ICE London", idx: [1] },
  { name: "portrait", sheet: "anil-dron", cat: "private", title: "Personal brand portrait", idx: [0, 26] },
  { name: "portrait-biz", sheet: "tasikn", cat: "private", title: "Business portrait", idx: [39] },
];

const OUT = path.join("..", "site", "img");
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });
const photos = [];
for (const p of PICKS) {
  const list = JSON.parse(fs.readFileSync(`sheets/${p.sheet}.json`, "utf8"));
  let n = 0;
  for (const i of p.idx) {
    const name = `${p.name}-${++n}`;
    const base = sharp(list[i]).rotate();
    const big = await base.clone().resize(2000, 2000, { fit: "inside", withoutEnlargement: true }).webp({ quality: 78 }).toFile(path.join(OUT, `${name}.webp`));
    await base.clone().resize(900, 900, { fit: "inside", withoutEnlargement: true }).webp({ quality: 72 }).toFile(path.join(OUT, `${name}-s.webp`));
    photos.push({ src: `img/${name}.webp`, thumb: `img/${name}-s.webp`, w: big.width, h: big.height, cat: p.cat, title: p.title });
  }
}
fs.writeFileSync(path.join("..", "site", "photos.js"), "// Generated by tools/export.mjs\nwindow.PHOTOS = " + JSON.stringify(photos.filter((x) => x.cat !== "about"), null, 1) + ";\n");
console.log("total", photos.length, "small:", photos.filter((x) => Math.max(x.w, x.h) < 1600).map((x) => x.src).join(" "));
